### ISSUE TITLE
Adjustable modbus timeout / interval?

### ISSUE THREAD

**Issue by kjeet90** [kjeet90/homey-ostberg-heru#15]
A user reported he is getting a modbus timeout when using a gateway. I suspect the problem is the gateway as the timeout is set to 1000ms as of now, but it doesn't hurt to make it configurable.

**Comment by Lindhardsen** [comment]
Let me know when you need someone to test this 👍

**Comment by kjeet90** [comment]
@Lindhardsen now available in test version [here](https://homey.app/en-us/app/no.kjeet90.ostbergheru/%C3%96stberg-Heru/test)

**Comment by Lindhardsen** [comment]
Kjetil it seems like you added polling interval instead of timeout? ☺️
Anyway I did try to change that to 4 or 5 seconds, but that did not change anything.

**Comment by kjeet90** [comment]
Modbus timeout is half of the poll interval

**Comment by kjeet90** [comment]
I won't make the timeout itself configurable, because if someone sets the timeout higher then the polling interval it will build up and eventually crash the app or Homey. There's not much more I can do about this then. I would suggest to try another gateway, or look more into it's settings, as others does not have this problem 🤔
