### ISSUE TITLE
temperature below zero

### ISSUE THREAD

**Issue by migoman958** [kjeet90/homey-ostberg-heru#2]
Thankyou for a great app!

When temperatures gets below zero - the app shows extreme values as +2500-6500 C

Is it something I can fix?

**Comment by kjeet90** [comment]
Thank you for reporting! I will look into it. I might need you to install a new version so I get some info about what is being sent from the Heru unit before I have a fix for it. My unit never report anything close to zero, so I am not able to test this myself.

**Comment by migoman958** [comment]
Very good – tell me what to do if needed.

 

Just to show how it looks:

 

Outdoor zero degrees and Outdoor below zero.

When waste air goes below Zero – it will also become 6500 degrees.

 

Regards

Mikael

 

Från: Kjetil Haugland ***@***.***> 
Skickat: Sunday, 26 March 2023 12:18
Till: kjeet90/homey-ostberg-heru ***@***.***>
Kopia: migoman958 ***@***.***>; Author ***@***.***>
Ämne: Re: [kjeet90/homey-ostberg-heru] temperature below zero (Issue #2)

 

Thank you for reporting! I will look into it. I might need you to install a new version so I get some info about what is being sent from the Heru unit before I have a fix for it. My unit never report anything close to zero, so I am not able to test this myself.

**Comment by kjeet90** [comment]
Could you try to install the test version and see if that helps with the negative values?
https://homey.app/no-no/app/no.kjeet90.ostbergheru/%C3%96stberg-Heru/test/

**Comment by migoman958** [comment]
It works just fine - I do now the outdoor temperature as -5°C !!
Soon my wast air will go below zero, Let's see what will happend. 
![20230328_202321000_iOS](https://user-images.githubusercontent.com/57372135/228359625-2804d3b7-f6a6-49dd-8065-c8ddf5b64019.png)
